name:                pure-asteroids
version:             0.1.0.0
github:              "honzaflash/ba-thesis/pure-asteroids"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/honzaflash/ba-thesis/pure-asteroids#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2 >= 2.5
- sdl2-ttf
- linear
- unordered-containers
- hashable
- lens
- random >= 1.2
# - parallel # Control.Parallel

library:
  source-dirs: src

executables:
  bench-p:
   main:                Main.hs
   source-dirs:         bench
   ghc-options:
   - -O
   - -threaded
   - -rtsopts
   - -with-rtsopts=-N
   dependencies:
   - pure-asteroids

#tests:
#  pure-asteroids-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - pure-asteroids
